language: python
python:
    - 3.6
sudo: required
services:
    - docker
install:
    - make -f travis-ci/Makefile test-env
script:
    - set -e
    - make -f travis-ci/Makefile build
    - make -f travis-ci/Makefile test
